@extends('layouts.website')
@section('content')
  <div class="row">
    <div class="col">
      <div class="text–center">
        <div class="card" style="text-align: justify;width:50%;padding:20px;margin-left:auto;margin-right:auto;">
          <h2>AVISO DE PRIVACIDAD</h2>

          CORPORATIVO POBLANO DE FRANQUICIAS S.A. DE C.V. con domicilio en AVENIDA JÚAREZ 2318 LOCAL "O" COL. LA PAZ, PUEBLA, PUEBLA, C.P. 72160 es responsable de recabar sus datos personales, del uso que se le dé a los mismos así como de su protección.<br />Recabamos sus datos personales de forma directa cuando usted mismo nos los proporciona por diversos medios, como:<br />ENCUESTAS DE CALIDAD, SERVICIO A DOMICILIO Y REDES SOCIALES.<br />Sus datos personales serán utilizados para las siguientes finalidades:<br />EXCLUSIVAMENTE PARA MARKETING INTERNO ASÍ COMO ESTADÍSTICA COMERCIAL, PUBLICACIÓN DE PROMOCIONES, EVENTOS, CONVENIOS Y BENEFICIOS VÍA CORREO ELECTRÓNICO Y REDES SOCIALES.<br />Para las finalidades señaladas en el presente aviso de privacidad, podemos recabar sus datos personales como:<br />NOMBRE, APELLIDO PATERNO, APELLIDO MATERNO, TELÉFONO, CELULAR, E-MAIL, EDAD, SEXO, FECHA DE NACIMIENTO, DIRECCIÓN, FOTOGRAFÍAS.<br />Le informamos que para cumplir con las finalidades previstas en este aviso de privacidad, NO serán recabados y tratados datos personales sensibles, como aquéllos que refieren a información financiera básica.<br />Usted tiene derecho de acceder, rectificar y cancelar sus datos personales, así como de oponerse al tratamiento de los mismos o revocar el consentimiento que para tal fin nos haya otorgado, a través de los procedimientos que hemos implementado. Para conocer dichos procedimientos, los requisitos y plazos, se puede poner en contacto con nuestro departamento de datos personales en AVENIDA JÚAREZ 2318 LOCAL "O" COL. LA PAZ, PUEBLA, PUEBLA, C.P. 72160, al teléfono (01- 222) 2 31 04 80 o al correo electrónico relacionespublicas@shirushi.mx , o visitar nuestra página de Internet <a href="https://l.facebook.com/l.php?u=http%3A%2F%2Fwww.shirushi.com.mx%2F%3Ffbclid%3DIwAR1mA1TkjqbSjYTBO__MBt_DaZ_NJme9q07T0nJRU9VPbrwpNWevVfMaBm8&amp;h=AT3mZ9n_ONhrkwC7c4XRSL22L7F6e5pSCUqFXJf5HIaqpuP3iXRLRwOsOf32vJa1OxdMKBT-5JAfoWjfDnQBLEhCp1dG_96Ru1Orz3XMySK7GE8OsXy6yQje4991FuBKgeXQlqpotqk" target="_blank" rel="noopener nofollow" data-lynx-mode="asynclazy">www.shirushi.com.mx</a><br />Si usted desea dejar de recibir mensajes promocionales de nuestra parte, puede solicitarlo a través del teléfono (01- 222) 2 31 04 80 o al correo electrónico relacionespublicas@shirushi.mx , o en el siguiente domicilio AVENIDA JÚAREZ 2318 LOCAL "O" COL. LA PAZ, PUEBLA, PUEBLA, C.P. 72160.<br />Cualquier modificación a este aviso de privacidad podrá consultarla en <a href="https://l.facebook.com/l.php?u=http%3A%2F%2Fwww.shirushi.com.mx%2F%3Ffbclid%3DIwAR2iR9uOvX_1C6IvMR09Tzqq0y_01KIrR0XnmBP6KKPu_HnJfXnUULZlywk&amp;h=AT14PHdIDI30-1d3PCj-Vrf4foQN4d10kPuZAk6_Hte30Zkc-releZB-eLLz_thGORghad-_SNiHPMCzaf-2JzoSNavlDK5oy9sCEQdwJ2f-Xu_xxBKdqaka_DhUCBjUP2FzU6qy9OA" target="_blank" rel="noopener nofollow" data-lynx-mode="asynclazy">www.shirushi.com.mx</a> <br />Fecha última actualización JUNIO 06, 2013, 15:26:46</p>
        </div>
      </div>
    </div>
  </div>
@endsection
